Added trailing 0 to ipv6 ranges that end in ":"
k8snetworkplumbingwg/whereabouts pull request #297
Opened 2023-01-26 22:10 UTC by nicklesimba

**What this PR does / why we need it**:
ipv6 ranges ending in a colon, such as a trail of zeroes denoted by "::" result in the storage engine failing to process the range, because ranges are expected to begin and end with alphanumerical characters to meet CRD requirements. Thus we append a 0 to any ranges that meet this criteria because it is functionally equivalent and meets the requirements.

Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
**Which issue(s) this PR fixes**:
Fixes #263, #293

**Special notes for your reviewer** *(optional)*:
https://imgs.xkcd.com/comics/networking_problems.png

2023-01-26 23:06 UTC, dougbtv requested changes
Totally on board with this change! Can we add a test that ends with a `::`?

Add another test near this one / like this one: https://github.com/k8snetworkplumbingwg/whereabouts/blob/master/cmd/whereabouts_test.go#L223-L235

2023-01-27 20:49 UTC, dougbtv requested changes

2023-01-27 20:49 UTC, dougbtv commented on cmd/whereabouts_test.go
> +		ipRange := "2001:1b74:480:603d:0304:0403:000:0000-2001:1b74:480:603d:0304:0403:0000:0004/64"
Let's use a documentation range, so make the range start with ` 2001:db8`

Also, add an additional test that doesn't just ends with zeros, but another one that ends with `::` literally so, for example.... `2001:db8:b33f::/48` or something

2023-01-27 20:49 UTC, dougbtv commented on cmd/whereabouts_test.go
> +		ipRange := "2001:1b74:480:603d:0304:0403:000:0000-2001:1b74:480:603d:0304:0403:0000:0004/64"
see also: https://www.rfc-editor.org/rfc/rfc3849.txt

2023-02-03 13:59 UTC, dougbtv commented
Looks good, I think we just need a rebase (there's a merge commit from master in here)

2023-02-08 15:04 UTC, dougbtv approved these changes
LGTM!

2023-02-08 15:04 UTC, merged

2023-02-08 15:06 UTC, maiqueb commented
wait, this merged a golang upgrade to 1.19. 

Do we want to do that ? 

Not saying I'm against it, but we probably should have merged https://github.com/k8snetworkplumbingwg/whereabouts/pull/294 instead first.

2023-02-09 09:05 UTC, adilGhaffarDev commented
@dougbtv can we cherry-pick this fix to v0.6?