prevent assigning outside of the requested range when excluding ranges
k8snetworkplumbingwg/whereabouts pull request #315
Opened 2023-03-30 09:35 UTC by bverschueren

**What this PR does / why we need it**:
This prevent overflowing outside the requested `ipam.range` when excluding ranges while the requested range is exhausted.

Also corrects a test where we expected to assign an IP outside of the expected range.

2023-03-31 18:36 UTC, andreaskaris requested changes
A few nits. Also, here are 2 more unit tests that fail. The first unit test can be addressed in a different PR, but the second unit test is the same test as yours (for the subnet) and using the end range. It's less critical than what you're fixing, but nevertheless it shows that it's possible to trick whereabouts to ignore the end range:
~~~
diff --git a/pkg/allocate/allocate_test.go b/pkg/allocate/allocate_test.go
index 47144c28..ab525c3d 100644
--- a/pkg/allocate/allocate_test.go
+++ b/pkg/allocate/allocate_test.go
@@ -453,6 +453,57 @@ var _ = Describe("Allocation operations", func() {
 
        })
 
+       // According to https://github.com/k8snetworkplumbingwg/whereabouts, we look at a range "... excluding the first
+       // network address and the last broadcast address".
+       It("the range start and end must be ignored if they are not with the bounds of the range for IPv4", func() {
+
+               _, ipnet, err := net.ParseCIDR("192.168.0.0/29")
+               Expect(err).NotTo(HaveOccurred())
+               rangeStart := net.ParseIP("192.168.0.0") // Network address, out of bounds.
+               newip, _, err := IterateForAssignment(*ipnet, rangeStart, nil, nil, nil, "0xdeadbeef", "")
+               Expect(err).NotTo(HaveOccurred())
+               Expect(fmt.Sprint(newip)).To(Equal(fmt.Sprint("192.168.0.1")))
+
+               _, ipnet, err = net.ParseCIDR("192.168.0.0/29")
+               Expect(err).NotTo(HaveOccurred())
+               rangeStart = net.ParseIP("192.168.0.0") // Network address, out of bounds.
+               rangeEnd := net.ParseIP("192.168.0.8")  // Broadcast address, out of bounds.
+               newip, _, err = IterateForAssignment(*ipnet, rangeStart, rangeEnd, nil, nil, "0xdeadbeef", "")
+               Expect(err).NotTo(HaveOccurred())
+               Expect(fmt.Sprint(newip)).To(Equal(fmt.Sprint("192.168.0.1")))
+
+       })
+
+       It("can IterateForAssignment on an IPv4 address excluding a range and respect endrange value", func() {
+
+               _, ipnet, err := net.ParseCIDR("192.168.0.0/28")
+               Expect(err).NotTo(HaveOccurred())
+               startip := net.ParseIP("192.168.0.1")
+               lastip := net.ParseIP("192.168.0.6")
+
+               ipres := []types.IPReservation{
+                       {
+                               IP:     net.ParseIP("192.168.0.1"),
+                               PodRef: "default/pod1",
+                       },
+                       {
+                               IP:     net.ParseIP("192.168.0.2"),
+                               PodRef: "default/pod1",
+                       },
+                       {
+                               IP:     net.ParseIP("192.168.0.3"),
+                               PodRef: "default/pod1",
+                       },
+               }
+               exrange := []string{"192.168.0.4/30"}
+               ip, _, err := IterateForAssignment(*ipnet, startip, lastip, ipres, exrange, "0xdeadbeef", "")
+               fmt.Println("VERIFICATION, SHOWS THAT 192.168.0.8 IS ASSIGNED, BUT SHOULD YIELD ERROR:", ip, err)
+               Expect(err).To(HaveOccurred())
+
+               Expect(err.Error()).To(HavePrefix("Could not allocate IP in range"))
+
+       })
+
        It("can IterateForAssignment on an IPv6 address excluding a range and stay within a requested range", func() {
 
                firstip, ipnet, err := net.ParseCIDR("100::2:1/125")
~~~

2023-03-31 18:36 UTC, andreaskaris commented on pkg/allocate/allocate_test.go
> +
Why the blank line here?

2023-03-31 21:15 UTC, nicklesimba commented
Hi Bram, functionally this looks great. I think after addressing nits re: unit testing we can go ahead with a merge.

2023-04-03 09:36 UTC, maiqueb requested changes
Thanks @andreaskaris for the review - you make good points.

2023-04-03 09:36 UTC, maiqueb commented on pkg/allocate/allocate_test.go
> +		Expect(err.Error()).To(HavePrefix("Could not allocate IP in range"))
Makes sense to me.

2023-04-03 09:36 UTC, maiqueb commented on pkg/allocate/allocate_test.go
> +
yes, please remove it.

2023-04-03 09:36 UTC, maiqueb commented on pkg/allocate/allocate_test.go
> +	It("can IterateForAssignment on an IPv4 address excluding a range and stay within a requested range", func() {
right. This test should be renamed.

2023-04-03 09:36 UTC, maiqueb commented on pkg/allocate/allocate_test.go
> +		calculatedrangestart := net.ParseIP(firstip.Mask(ipnet.Mask).String())
nice catch.

2023-04-03 10:28 UTC, andreaskaris commented
/retest

2023-04-03 10:45 UTC, maiqueb commented
@bverschueren you may be missing a `go mod tidy && go mod vendor` call. 

Please push that as a separate commit.

2023-04-03 11:09 UTC, maiqueb commented
Hm no, I think the `netip` pkg simply did not exist on golang 1.17, which is the base img the openshift images uses. 

I'll try to bump that in a separate PR, give me some time please.
@bverschueren / @andreaskaris

2023-04-03 11:12 UTC, andreaskaris commented
Ah that's my bad then ... sorry ... So let's just remove the changes to `func (a AssignmentError) Error() string {` --- sorry for being overly zealous!

2023-04-03 11:15 UTC, maiqueb commented
It might be OK @andreaskaris ; #319 fixes it, as can be seen in https://github.com/k8snetworkplumbingwg/whereabouts/actions/runs/4595981928/jobs/8116884713?pr=319

2023-04-03 11:16 UTC, andreaskaris commented
Yes but that PR change must be backported, won't that create issues?

2023-04-03 11:18 UTC, maiqueb commented
> Yes but that PR change must be backported, won't that create issues?

Hm, right - I forgot this had to be backported. 

Right, maybe better to remove those.

I'd still ask for a review of #319 from you; that would still make sense to have in master. 

You can then push a separate PR (which we will **not** backport) to improve the error msg.

2023-04-03 11:21 UTC, andreaskaris commented
Sounds good - so @bverschueren sorry for the confusion here.

a) Remove my suggested changes from: `func (a AssignmentError) Error() string {` so that your PR is a minimal set of changes to address the urgent issue at hand
b) I'll create a new PR with the change to `func (a AssignmentError) Error() string {` as a follow-up
c) I'll create a new PR that contains the unit tests that I talked about earlier, and fixes for those, as a follow-up

2023-04-03 11:46 UTC, bverschueren commented
Right @andreaskaris @maiqueb we're back at the minimal change to fix the subnet overflow.

2023-04-03 12:36 UTC, maiqueb approved these changes
lgtm.

I'll leave the merge for @dougbtv .

2023-04-03 14:44 UTC, merged